name: Continous Integration (CI)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build and Test with Coverage
        run: ./gradlew clean build jacocoTestReport

      - name: Cek Lokasi File XML
        run: ls -R build/reports/

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=B-Bisma-Zharfan-SW-2406355136_Modul-2-CI-CD-DevOps
            -Dsonar.organization=b-bisma-zharfan-sw-2406355136
            -Dsonar.java.binaries=build/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_KEY }}